### ISSUE TITLE
List presentation options

### ISSUE THREAD

**Issue by thorwhalen** [i2mint/py2dash#3]
Enable different ways of presenting the set/list of functions we are dispatching. Now it's a vertical list, but would be nice to tell config to do horizontal list instead, or drop down,  or "virtual tabs", etc.. Showing/searching a list is a very common pattern, so we'd like to have possibilities for this. See, for example: http://ui-patterns.com/users/1/collections/lists/screenshots

**Comment by SRHerzog** [comment]
In Dash, the way to add your own CSS is to just save a file in the project's `assets` directory (see https://dash.plot.ly/external-resources). This is inconvenient for us because the stylesheet can't be easily imported and manipulated in Python.

My suggestion is to have a set of CSS files in py2dash with a default class for each component as well as some optional classes. At runtime, we then need to copy those files into the `./assets` directory relative to the entrypoint script that is importing py2dash.

Later, we could add plugin support by allowing clients to pass flags to some function in the app startup to import CSS and copy CSS files from any other library prefixed with `py2dash_` (for example), either for the entire app at once or on a per-component basis.
